global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'wg-orbit-server'
    static_configs:
      - targets: ['wg-orbit-server:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'wg-orbit-client'
    static_configs:
      - targets: ['wg-orbit-client:8081']
    metrics_path: '/metrics'
    scrape_interval: 30s